# Generated by Django 4.0.4 on 2022-06-09 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('excerto', models.TextField()),
                ('qdt_volumes', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='novel_img/%Y/%m/%d')),
                ('wallpaper', models.ImageField(upload_to='novel_wall/%Y/%m/%d')),
                ('publicado', models.BooleanField(default=False)),
                ('outros_titulos', models.CharField(max_length=150)),
                ('escritor', models.CharField(max_length=50)),
                ('ilustrador', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=25)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_vol', models.CharField(max_length=50)),
                ('titulo_vol', models.CharField(max_length=50)),
                ('capa_vol', models.ImageField(upload_to='vol_capa/%Y/%m/%d')),
                ('num_vol', models.IntegerField()),
                ('descriacao_vol', models.TextField()),
                ('data_vol', models.DateTimeField(default=django.utils.timezone.now)),
                ('novel_vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novel')),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cap', models.CharField(max_length=100)),
                ('conteudo_cap', models.TextField()),
                ('data_cap', models.DateTimeField(default=django.utils.timezone.now)),
                ('volume_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.volume')),
            ],
        ),
    ]
