# Generated by Django 4.0.4 on 2022-07-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='titulo_vol',
        ),
        migrations.AddField(
            model_name='capitulo',
            name='numero_cap',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capitulo',
            name='slug_cap',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='slug_vol',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
